# Generated by Django 4.1.7 on 2023-09-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanuser',
            name='uuid',
            field=models.CharField(default=None, max_length=12),
        ),
    ]
