# Generated by Django 4.1.7 on 2023-09-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loanuser_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanuser',
            name='uuid',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
    ]
