# Generated by Django 4.0 on 2023-09-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_alter_loanuser_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanuser',
            name='uuid',
            field=models.CharField(default='default', max_length=12),
        ),
    ]
