# Generated by Django 4.0 on 2023-09-18 09:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_alter_loanuser_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='loan_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
