# Generated by Django 4.1.7 on 2023-09-18 15:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_loanapplication_loan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='loanuser',
            name='credit_score',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='loanuser',
            name='uuid',
            field=models.CharField(default='default', editable=False, max_length=12),
        ),
    ]
